<?php

createVolume_successful
createVolume_invalidVolume
createVolume_invalidNumber
createVolume_invalidYear
createVolume_invalidMonth
createVolume_missingCoverImage
createVolume_invalidCoverImage
collectVolumes_empty
collectVolumes_multiple
getVolumeById_successful
getVolumeById_invalidId
updateVolume_successful
updateVolume_invalidId
updateVolume_invalidVolume
updateVolume_invalidNumber
updateVolume_invalidYear
updateVolume_invalidMonth
updateVolume_missingCoverImage
updateVolume_invalidCoverImage
removeVolume_successful
removeVolume_invalidId
removeVolume_inUse

?>
