<?php

createArticle_successful
createArticle_invalidType
createArticle_missingTitle
createArticle_invalidVolumeId
createArticle_invalidFirstPage
createArticle_invalidLastPage
createArticle_invalidPageInterval
createArticle_invalidDocumentId
collectArticlesByVolume_empty
collectArticlesByVolume_multiple
collectArticlesByVolume_invalidId
getArticleById_successful
getArticleById_invalidId
updateArticle_successful
updateArticle_invalidId
updateArticle_invalidType
updateArticle_missingTitle
updateArticle_invalidVolumeId
updateArticle_invalidFirstPage
updateArticle_invalidLastPage
updateArticle_invalidPageInterval
updateArticle_invalidDocumentId
removeArticle_successful
removeArticle_invalidId

?>
